### ISSUE TITLE
openid auth provider

### ISSUE THREAD

**Issue by everpcpc** [douban/helpdesk#2]
Add support for multiple openid providers, then resetting ldap password is acceptable when authorized with google.

**Comment by LeoQuote** [comment]
想用程序调用的时候发现还是有些困难, 还要加一个能 header 直接验证的middleware , 
```
Authorization: Bearer {{ id_token }}
```

**Comment by LeoQuote** [comment]
id_token 里一般都会有 iss, 也就是issuer, 应该可以用来选择对应的配置

**Comment by LeoQuote** [comment]
想到了一个hack, get 到了 access_token 之后 直接 get `/callback/{provider}` , 这样就也可以过验证.
