### ISSUE TITLE
Frontend checkbox after check and uncheck will still remain as checked

### ISSUE THREAD

**Issue by dispensable** [douban/helpdesk#28]
1. check the checkbox
2. uncheck the checkbox
3. submmit and the value is checked value

**Comment by LeoQuote** [comment]
前端传过去的值是字符串 "false",后端在这里只要有值就是 True
https://github.com/douban/helpdesk/blob/bb8ce66150090d37db109829410c1c4b4eec5260/helpdesk/models/action.py#L74-L77 

在这改一下就行

**Comment by dispensable** [comment]
哈哈哈，这 if bool = true 给我看笑了
