### ISSUE TITLE
本地开发时, 本地产生的 500 exception traceback 应该打印在控制台内

### ISSUE THREAD

**Issue by LeoQuote** [douban/helpdesk#92]
现在本地都不知道怎么调试了, 就离谱, 还得上线才能看到效果

登录也是的, cookie 也set 不成功, 真的不知道以前都是怎么开发的. 现在又多了些什么鬼东西

**Comment by dispensable** [comment]
是被捕获了，预期行为，加个配置，确实有点迷惑。

**Comment by dispensable** [comment]
可以考虑加个pde支持，这样开发会舒服点

**Comment by LeoQuote** [comment]
是被apierror捕获还是sentry捕获了啊🤔，响应里有traceback 也很离谱...

**Comment by dispensable** [comment]
被错误处理捕获了，而且还把eception转成了json

**Comment by LeoQuote** [comment]
> 被错误处理捕获了，而且还把eception转成了json

😂😂😂 真有你的helpdesk

**Comment by LeoQuote** [comment]
helpdesk/views/api/errors.py 应该是这里的错误处理吧，直接去掉就好了吧

**Comment by LeoQuote** [comment]
已解决
